- name: meat provisioning the chats
  hosts: "{{ chat_name }}:default"

  vars:
    app_home: ~/{{ chat_name }}

  pre_tasks:
    - name: cloning meatspace-chat repository
      git: >
        repo={{ meatspace_repo }}
        dest={{ app_home }}
        version={{ meatspace_version }}

    - name: installing meatspace-chat dependencies
      shell: chdir={{ app_home }} {{ item }}
      with_items:
        - npm install
        - bower install
        - grunt build

    - name: installing meatspace configuration
      template: src={{ item }} dest={{ app_home }}/
      register: configs
      with_items:
        - templates/local.json
        - templates/clients.json
        - templates/whitelist.json

  roles:
    - role: eggsby.supervise
      name: "{{ chat_name }}"
      command: node app.js

  tasks:
    - name: restarting meatspace
      supervisorctl: name={{ chat_name }} state=restarted {{ super_args }}
      when: configs|changed
